volumes:
  database: {}

services:
  http:
    build:
      context: .
      target: http
    ports:
      - "${BIND_PORT_HTTP:-8000}:8888"
      - "${BIND_PORT_HTTPS:-8001}:8889"
    env_file:
      - .env
    volumes:
      - ./certs:/certs
      - database:/data

  ssh:
    build:
      context: .
      target: ssh
    ports:
      - "${BIND_PORT_SSH:-8022}:8022"
    env_file:
      - .env
    volumes:
      - database:/data
